id: P010637
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18667
  title: ཁེ་དབང་སྲུང་སྐྱོང་དང་ཡིག་སྐུར་ངོ་གཏུག་སྐོར་གྱི་བཅའ་ཁྲིམས་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  volumes:
    cbe0bc234d9f4ca9ac261dc365058f47:
      image_group_id: I8LS18669
      title: ''
      volume_number: 1
      total_pages: 143
